# Generated by Django 4.2.5 on 2023-09-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(default='write here')),
            ],
        ),
    ]
